version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:      
      - MONGO_INITDB_DATABASE=ProductDb      
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
